# Generated by Django 4.2.2 on 2023-07-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='is_ongoing',
            field=models.BooleanField(default=True),
        ),
    ]
