# Generated by Django 4.2.2 on 2023-07-11 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_projects_is_ongoing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
