# Generated by Django 4.2.2 on 2023-07-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_rename_projects_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.ImageField(default='default_image.png', upload_to='project_images/'),
        ),
    ]
