# Generated by Django 4.2.2 on 2023-07-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_alter_project_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('project_image', models.ImageField(default='default_image.png', upload_to='project_images/')),
            ],
        ),
    ]
