# Generated by Django 4.2.2 on 2023-07-23 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0008_alter_service_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='project_image',
            new_name='service_image',
        ),
    ]
