# Generated by Django 4.2.2 on 2023-07-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0009_rename_project_image_service_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('product_image', models.ImageField(default='default_product_image.png', upload_to='products_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='service_image',
            field=models.ImageField(default='default_service_image.png', upload_to='service_images/'),
        ),
    ]
