# Generated by Django 4.2.2 on 2023-07-29 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0010_products_alter_service_service_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
