# Generated by Django 4.2.2 on 2023-07-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0012_alter_product_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='default_image.jpg', upload_to='products_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(default='default_image.jpg', upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_image',
            field=models.ImageField(default='default_image.jpg', upload_to='service_images/'),
        ),
    ]
